issue-381 : Remove additional setup script of kafka, zookeeper
bharath-b23/ODIM pull request #14
Opened 2021-02-13 08:10 UTC by bharath-b-hpe

2021-02-15 03:38 UTC, jeevan-kamkar approved these changes

2021-02-15 03:39 UTC, rahulroshan-kachchap approved these changes

2021-02-16 13:18 UTC, skhan-anjum approved these changes

2021-02-16 14:49 UTC, a-ajith approved these changes

2021-02-16 15:05 UTC, Bharath-KKB requested changes
we should be pulling from dev branch rather than patching like this.

2021-02-17 08:11 UTC, Bharath-KKB approved these changes

2021-02-17 08:11 UTC, merged